<?php
putenv('BOLSO_DB_HOST=127.0.0.1');
putenv('BOLSO_DB_PORT=3306');
putenv('BOLSO_DB_NAME=Bolsodb');
putenv('BOLSO_DB_USER=Bolsodb');
putenv('BOLSO_DB_PASSWORD=FAsBc8WKE3IGy2cppGnt');
putenv('BOLSO_WHATSAPP=919674773475');
putenv('BOLSO_PAYMENT_KEY=rzp_test_TXHzubPWVcRrT7');
putenv('BOLSO_PAYMENT_SECRET=WBOpN3a5npmtmWHNc5wIREEN');
putenv('BOLSO_ADMIN_EMAIL=10abhishekkr@gmail.com');
putenv('BOLSO_ADMIN_WHATSAPP=919341469219');